### ISSUE TITLE
can you package react-native-linkedin-login by rnpm on ios?

### ISSUE THREAD

**Issue by 277850318** [jodybrewster/react-native-linkedin-login#14]
it's too hard Install by  the Cocoapods  for me.

**Comment by jreziga** [comment]
Very painful for me too. I followed instructions but it didn't worked...

**Comment by sheerun** [comment]
It doesn't work with `react-native link` as well

**Comment by jodybrewster** [comment]
I'm going to start looking into it. Sorry about the delay.

**Comment by jr-k** [comment]
@jodybrewster better now than never 😄

**Comment by jodybrewster** [comment]
I've removed cocopods, looking into rnpm
