### ISSUE TITLE
cannot find symbol new RNLinkedinLoginPackage()

### ISSUE THREAD

**Issue by ChrisCates** [jodybrewster/react-native-linkedin-login#15]
```
/Users/chriscates/projects/meetf2f/android/app/src/main/java/com/meetf2f/MainApplication.java:7: error: cannot find symbol
import com.linkedin.android.mobilesdk.RNLinkedinLoginPackage;
                                     ^
  symbol:   class RNLinkedinLoginPackage
  location: package com.linkedin.android.mobilesdk
/Users/chriscates/projects/meetf2f/android/app/src/main/java/com/meetf2f/MainApplication.java:31: error: cannot find symbol
            new RNLinkedinLoginPackage(),
                ^
  symbol: class RNLinkedinLoginPackage
/Users/chriscates/projects/meetf2f/android/app/src/main/java/com/meetf2f/MainApplication.java:32: error: cannot find symbol
            new RNLinkedinLoginPackage(this),
                ^
  symbol: class RNLinkedinLoginPackage
3 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

Here's the dump of the issues... Any reason why the library won't work?

**Comment by mlumbroso** [comment]
My import is as followed and works :

```
import net.jodybrewster.linkedinlogin.RNLinkedinLoginModule;       
import net.jodybrewster.linkedinlogin.RNLinkedinLoginPackage;
import com.linkedin.platform.LISessionManager;   
```

and then i call `new RNLinkedinLoginPackage(),`

**Comment by ChrisCates** [comment]
Mine came from `react native link`

I used those imports and it required a parameter???

**Comment by mlumbroso** [comment]
I guess there is a problem with autolinking then...

What do you mean by it required a parameter?

**Comment by ChrisCates** [comment]
@mlumbroso It asked for an argument inside the function call.

**Comment by arisAlexis** [comment]
@ChrisCates 

the instructions say you should put these into the MainActivity.java and there is no mention of linking. Although I am struggling to make it work too.

**Comment by ChrisCates** [comment]
@arisAlexis Thanks, but from needing to do a PR on this... PR on React-Native-Maps and a whole swath of PRs I have to do on the React-Native library.

I've decided to do Java and Swift instead.
I'm most likely going to rewrite Jody's library since it'll be easier for me then figuring out what he did (plus I can start off with latest version of React).

**Comment by ChrisCates** [comment]
Lets be honest here. The last commit was August 16th. He's clearly not taking this project seriously...

**Comment by arisAlexis** [comment]
@ChrisCates he could keep the code for himself as it is apparent that was used for another project but it is open source and we can't complain

**Comment by jodybrewster** [comment]
I've made some significant changes to the project and I'm moving it to rnpm here soon so we won't get into this issue, sorry for the delay
