### ISSUE TITLE
IOSLinkedInAPI main thread issue.

### ISSUE THREAD

**Issue by tauqeer-ahmad** [jodybrewster/react-native-linkedin-login#17]
I was getting an error on IOS "Accessing _chachedSystemFence needs main thread". this only happens when user login and perform some tasks e.g (post some thing to server) and then logout. After logout if he tries to login again this above error popped. 

To fix this I have update my pods for IOSLinkedInAPI [https://github.com/tauqeer-ahmad/IOSLinkedInAPI/blob/master/IOSLinkedInAPI/LIALinkedInHttpClient.m](https://github.com/tauqeer-ahmad/IOSLinkedInAPI/blob/master/IOSLinkedInAPI/LIALinkedInHttpClient.m) 

`+dispatch_sync(dispatch_get_main_queue(), ^{
        [self.presentingViewController presentViewController:nc animated:YES completion:nil];
  +});` to get the main thread. 

I'm looking for a way to specify my forked repo path for IOSLinkedInAPI in react-native-linkedin-login podspecs. Any ideas?

**Comment by Richard-Cao** [comment]
any thing else?

**Comment by jodybrewster** [comment]
I've removed cocoapods entirely in the latest so hopefully this helps.
