### ISSUE TITLE
Login opens linkedin app and does nothing

### ISSUE THREAD

**Issue by arisAlexis** [jodybrewster/react-native-linkedin-login#18]
I am using the setup by the fork that works with react 0.35+ https://github.com/alma-connect/react-native-linkedin-login for android.

When I hit the login button the linkedin app seems to open momentarily but  then does nothing. 
`LinkedinLogin.login().then(user => { console.log('got user') }).catch((e) => console.log('error'));` this line doesn't produce any output

Does anyone else experience this problem?

**Comment by SerzN1** [comment]
Hi. Probably you don't init module or params wrong.

**Comment by arisAlexis** [comment]
Not really, all params are correct and the mobule is initialized as per documentation.

```
import LinkedinLogin from 'react-native-linkedin-login';

LinkedinLogin.init(
      'http://therecord.io',
      'client_id',
      'client_secret',
      'app_hash',
      [
        'r_emailaddress',
        'r_basicprofile'
      ]
    );

 LinkedinLogin.login().then((user) => {
      console.log('User logged in: ', user);
    })
    .catch((e) => console.log(e));
```

this outputs nothing on the console.

**Comment by jodybrewster** [comment]
Looking into it, sorry for the delay

**Comment by jodybrewster** [comment]
Updated the project with a working version
