### ISSUE TITLE
LinkedinLogin.h:27:9: fatal error: 'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by SerzN1** [jodybrewster/react-native-linkedin-login#19]
Hello. How can I solve this problem? Any ideas?

**Comment by SerzN1** [comment]
http://take.ms/Wm5ft here is xCode error message

**Comment by SerzN1** [comment]
If I use "use_frameworks!" in my Podfile it fails with error.
How can I combine "use_frameworks!" flag with this module?

**Comment by geordasche** [comment]
@SerzN1, if you're still having this problem, you can try adding a path reference to your react native headers in your Pods project (Pods.xcodeproj). 
Example:
```
Project -> Build Settings -> User Header Search Paths -> $(SRCROOT)/../../node_modules/react-native/React
```
and make it recursive. Hope this helps.

**Comment by jodybrewster** [comment]
I've removed cocoapods from the project, I'm also moving to rnpm, so hopefully that eases installs.
