### ISSUE TITLE
Cannot evaluate module react-native-linkedin-login

### ISSUE THREAD

**Issue by navaneeth** [jodybrewster/react-native-linkedin-login#2]
I have followed everything specified in the android setup guide. I am getting the following error

```
Cannot evaluate module react-native-linkedin-login. Configuration with name 'default' not found.
```

My `package.json` looks like the following

```
{
  "dependencies": {
    "react-button": "^1.2.1",
    "react-native": "^0.20.0",
    "react-native-dialogs": "0.0.13",
    "react-native-facebook-login": "^1.0.3",
    "react-native-file-transfer-android": "0.0.2",
    "react-native-linkedin-login": "^1.2.2",
    "react-native-loading-spinner-overlay": "0.0.6",
    "react-native-modalbox": "^1.3.1",
    "react-native-navbar": "^1.4.2",
    "react-native-parallax": "^0.2.2",
    "react-native-scrollable-tab-view": "^0.4.0",
    "react-native-selectme": "^1.0.0",
    "react-native-vector-icons": "^1.3.3"
  }
}
```

Any idea why this error will happen? Any help would be great.

**Comment by xphaul** [comment]
@navaneeth did you managed to solve this problem?

**Comment by xphaul** [comment]
@jodybrewster same as @navaneeth im getting this error when compiling this on an android device i have also followed all of the guides in setting this up . Thanks

**Comment by xphaul** [comment]
okay i managed to make it run . i just changed 
project(':react-native-linkedin-login').projectDir = new File(rootProject.projectDir, '../../android')
to
project(':react-native-linkedin-login').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linkedin-login/android')

hope this helps other devs on the future . cheers

**Comment by mlumbroso** [comment]
Thanks had the same issue and this solved it !

**Comment by xphaul** [comment]
@mlumbroso can you check if theres a returned promise if you succesfully logged in #7 im stuck with this thanks

**Comment by mlumbroso** [comment]
Actually, I can't help you because I'm stuck before, with this error :

`"{
  "errorCode": "INVALID_REQUEST",
  "errorMessage": "either bundle id or package name \/ hash are invalid, unknown, malformed"
}"`

I'm not sure what parameter was wrong. I'm using it on Android :

'your_client_id',
    'your_client_secret',
    'your_state',

actually the your_state parameter I have no clue what it corresponds to. You have any clue?

Thanks

**Comment by arisAlexis** [comment]
@mlumbroso I have no clue either for the state. Can you please elaborate what is the hash generation?
