### ISSUE TITLE
'RCTLinkedinLogin/RCTLinkedinLogin.h' file not found

### ISSUE THREAD

**Issue by dittmarconsulting** [jodybrewster/react-native-linkedin-login#26]
Steps to reproduce error:

1. Create a new project `react-native init LNTest`
2. `cd` into the newly created folder LNTest
3. Install package `npm install --save react-native-linkedin-login`

      ```
      "react": "16.0.0-alpha.12",
      "react-native": "0.45.0",
      "react-native-linkedin-login": "^1.44.1"
      ```

4. Link library `react-native link react-native-linkedin-login`
5. Open XCode (8.3.2)
6. Clean & Build project (succeeded)
7. Drop `RCTLinkedinLogin.xcodeproj` into the project
8. Add `#import <RCTLinkedinLogin/RCTLinkedinLogin.h>` to AppDelegate.m file

Header Search Path: `$(SRCROOT)/../node_modules/react-native-linkedin-login/ios/RCTLinkedinLogin`

![screenshot 2017-06-08 17 57 21 2](https://user-images.githubusercontent.com/19203201/26918127-08107208-4c74-11e7-8c6d-9ec63b78b2d0.png)

**Comment by jodybrewster** [comment]
Thanks, I'll test this soon and get back to you.

**Comment by dittmarconsulting** [comment]
Replacing `<RCTLinkedinLogin/RCTLinkedinLogin.h>` with `"RCTLinkedinLogin.h"` fixed the problem

**Comment by sregg** [comment]
@dittmarconsulting I had the same issue and fixed it using your solution.
But it feels pretty hacky. Did you end up keeping it in your project or did you manage to make it work using `<RCTLinkedinLogin/RCTLinkedinLogin.h>`?

**Comment by prih** [comment]
@sregg just Header Search Path must be: $(SRCROOT)/../node_modules/react-native-linkedin-login/ios
