### ISSUE TITLE
Bitcode bundle could not be generated ...

### ISSUE THREAD

**Issue by dittmarconsulting** [jodybrewster/react-native-linkedin-login#29]
The sample project builds and runs fine but it doesn't archive for pushing to App Store (TestFlight) I get the following error msg:

```Bitcode bundle could not be generated because ... libRCTLinkedinLogin.a(Pods-dummy.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7```

Env vars

    react - 16.0.0-alpha.12
    react-native - 0.45.0
    react-native-linkedin-login - 1.44.1
    Xcode - 8.3.2
    iOS - 10.3

**Comment by dittmarconsulting** [comment]
Any update on this issue? I really need a solution soonish.

I'd love to resolve it myself but my Objective C/Swift knowledge is very limited.

Thank you in advance.

**Comment by Misioka** [comment]
You can simply disable Bitcode build https://stackoverflow.com/questions/30848208/new-warnings-in-ios-9
Or you can update LinkedIn SDK in this library to 1.0.6 whitch supports bitcode.

**Comment by dittmarconsulting** [comment]
That worked fine. Thanks for that.

**Comment by slestang** [comment]
I try to update the Linkedin SDK to its latest version (1.0.7 taken here https://content.linkedin.com/content/dam/developer/sdk/iOS/li-ios-sdk-1.0.7-release.zip) but it seems this project already has the latest version (I compare the md5 of each files).

But I have still the same bitcode error :-(

I look into the binary and it seems that the bitcode is here:
```
$ otool -arch armv7 -l li-ios-sdk-1.0.7-release/linkedin-sdk.framework/linkedin-sdk
...
li-ios-sdk-1.0.7-release/linkedin-sdk.framework/linkedin-sdk(Pods-dummy.o):
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedface      12          9  0x00           1     8       1952 0x00002000
...
Section
  sectname __bitcode
   segname __LLVM
      addr 0x00000758
      size 0x00000001
    offset 3860
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
...
```
Does anybody have an idea on why it isn't building?

**Comment by jacobbodkin** [comment]
@slestang were able to find a solution to this? I have the latest sdk but am still getting the same error. Also if I disable bitcode i get an error telling me to enable it.

**Comment by Misioka** [comment]
@slestang & @jacobbodkin You have to manually download LinkedIn SDK with bitcode support. https://developer.linkedin.com/docs/mobile-sdk-release-notes#ios
That works for me.

**Comment by jacobbodkin** [comment]
@Misioka i thought i knew who to do this by replacing linkedin-sdk under RCTLinkedinLogin.xcodeproj but that did not work. Suggestions?
