### ISSUE TITLE
Linker command failed, linkedin sdk does not contain bitcode

### ISSUE THREAD

**Issue by jiangyuanhk** [jodybrewster/react-native-linkedin-login#3]
Not sure if related. 

When I added (copied) `RNLinkedinLogin` folder into project folder in Xcode, and trying to build it.  The project builds successfully when running emulator, but fails with the device.  Only by set `Enable Bitcode` option in _General -> Build Settings -> Build Options_ to `No` can I resolve the issue.  

Below is a screen cast
<img width="1319" alt="screen shot 2016-04-16 at 11 18 37 pm" src="https://cloud.githubusercontent.com/assets/7784875/14584923/2ed96dc6-042d-11e6-8ee3-e3da7f45b1f1.png">

**Comment by jodybrewster** [comment]
@jiangyuanhk I've moved everything to cocoa pods so this should be fixed.
