### ISSUE TITLE
No linkedIn App Installed iOS

### ISSUE THREAD

**Issue by Misioka** [jodybrewster/react-native-linkedin-login#31]
If I have no app installed on iPhone.
Nothing happend.
I try to debug native but everything what i find out is that LinkedIn SDK returns false for shouldHandleUrl.

Can you help me please?
`- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  NSLog(@"%@ shouldHandle=%@", url, [RCTLinkedinLogin shouldHandleUrl:url] ? @"Yes" : @"No");
  if ([RCTLinkedinLogin shouldHandleUrl:url])
  {
    return [RCTLinkedinLogin application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
  }
  return Yes;
}`

**Comment by dittmarconsulting** [comment]
Related to [#28](https://github.com/jodybrewster/react-native-linkedin-login/issues/28)

**Comment by jodybrewster** [comment]
Closing this and keeping #28 open
