### ISSUE TITLE
onActivityResult not invoked after login

### ISSUE THREAD

**Issue by mancas** [jodybrewster/react-native-linkedin-login#33]
Hi! I'm trying to setup the library and everything works fine until I perform the login, because no data is returned.

After take a deep look at the library and add a few traces I've noticed that the `onActivityResult` method is never called so no result is delivered to the react app.

Any ideas on this? This is my configuration:

````
{
  "name": "Pikis",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-preset-react-native": "^4.0.0",
    "jest-expo": "~20.0.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "Root.js",
  "scripts": {
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^20.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
    "react-native-elements": "^0.17.0",
    "react-native-fbsdk": "^0.6.1",
    "react-native-linkedin-login": "^1.44.1",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "uuid": "^3.1.0"
  }
}

````

Thanks

**Comment by iuliuvisovan** [comment]
This happens for a while now on both react native linkedin packages (react-native-linkedin-sdk / react-native-linkedin-login).. so I think it should have something to do with the code linkedin sdk.. any ideas?

**Comment by jodybrewster** [comment]
Sorry for the long delay, I'm looking into this now this is related to #36 to closing this issue
