### ISSUE TITLE
LinkedIn implementation

### ISSUE THREAD

**Issue by isaacvigil** [jodybrewster/react-native-linkedin-login#4]
Hello,
when implementing oAuth (for LinkedIn) inside a React Native WebView Component, Once successfully logged in and the uri-redirect is initiated, how do I trigger and pass the token back into the non-WebView React Native Component or store it asyncStorage for future use. Either using Promises, async/await or any alternative method of delivery.
Thank you.

**Comment by jodybrewster** [comment]
@isaacvigil I'd refer all questions to StackOverflow, sorry mate, I'm a busy guy
