### ISSUE TITLE
Native Linkedin app login

### ISSUE THREAD

**Issue by coatezy** [jodybrewster/react-native-linkedin-login#5]
Hey Jody,

I've setup your library and it's working nicely. I was wondering if it is currently possible to authenticate using the official Linkedin app if it is install on the user device and if not fall back to the web view version? I currently only see the web view version even though I have the official app installed.

Cheers
Tom

**Comment by jodybrewster** [comment]
@coatezy Are you on iOS or Android?

**Comment by shraddha1704** [comment]
Hey Jody,

I've integrated this module in my react-native project. I'm currently on Android. When I use the login function, it authenticates if there is a linkedIn app installed on my phone. If it's not installed it gives a popup to install on my phone. Is it possible to open a webview in this case?

Regards,
Shraddha

**Comment by coatezy** [comment]
@jodybrewster experiencing this on iOS.

**Comment by jodybrewster** [comment]
Closing this, I use the official API that Linkedin provides.
