### ISSUE TITLE
[Android]: Login does not return any promise

### ISSUE THREAD

**Issue by xphaul** [jodybrewster/react-native-linkedin-login#7]
![screen shot 2016-06-20 at 3 16 23 pm](https://cloud.githubusercontent.com/assets/12995157/16185944/0bec1868-36fa-11e6-84ee-37ac253811ef.png)

@jodybrewster  there is no data being logged after i have successfully logged in

**Comment by mlumbroso** [comment]
So, I had the same issue, it disappears when I change on the button

`onPress={ this._login }`

with 

`onPress={() => { this._login(); } }`

Although there is the same error now with this, again a scope problem :
 _this4._getUserProfile is not a function

**Comment by jodybrewster** [comment]
I'm going to start supporting promises soon, closing this for now
