### ISSUE TITLE
[iOS] After webview login : Authorization failed Error Domain=LIALinkedInERROR Code=2 "(null)"

### ISSUE THREAD

**Issue by mlumbroso** [jodybrewster/react-native-linkedin-login#8]
Hi,

thanks for this very useful plugin. I've successfully used it on Android, but I have some trouble in iOS, at least testing on simulator in Webview. I see the login page, I can identify myself, then it closes the webview and does move forward, with this error on console :

Authorization failed Error Domain=LIALinkedInERROR Code=2 "(null)"

Any idea what could be wrong there?

Thanks

**Comment by mlumbroso** [comment]
It is probably linked to this : http://stackoverflow.com/questions/30232359/ios-linkedin-api-error/37583830#37583830

Maybe you should update SDK to 1.0.7 ? Don't know if it will fix the problem though...

**Comment by mlumbroso** [comment]
I saw  there was a pullrequest about it that was merged, can you just update the npm package then?

If not possible I'll get directly from Github the last version I guess.

**Comment by jodybrewster** [comment]
@mlumbroso Thanks this has been fixed.
