### ISSUE TITLE
 [Android] Update doc for compatibity with RN 0.30+

### ISSUE THREAD

**Issue by mlumbroso** [jodybrewster/react-native-linkedin-login#9]
Hi,

since changes from MainActivity to MainApplication, the instructions don't work anymore.

Any chance to have an update soon?

Thanks

**Comment by jodybrewster** [comment]
@mlumbroso Yes soon! Finally I have some time! weeeeeee

**Comment by mlumbroso** [comment]
I think I made it work, will update tomorrow with what I did at the end :-)

**Comment by jodybrewster** [comment]
I moved everything to cocoapods so you may want to pull

**Comment by assem-ch** [comment]
is this issue fixed ?

**Comment by luisfuertes** [comment]
This component works on Android and iOS with RN `v0.33.0`?

**Comment by mlumbroso** [comment]
On 0.32 it does, so I don't think there should be any issue with 0.33

**Comment by Tohix** [comment]
Can you please update doc for RN 0.35? If you have already build application with new version RN, please help.

**Comment by luisfuertes** [comment]
Im trying to implement the component on Project with RN `v0.33.0`.
At the moment:

**`android/app/build.gradle`**: 
```
include ':react-native-linkedin-login'
project(':react-native-linkedin-login').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-linkedin-login/android')

include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
```

**`android/build.gradle`**: 
```
    compile project(":react-native-linkedin-login")
    compile project(':react-native-vector-icons')
``` 

**`MainAplication`**: 
```
import net.jodybrewster.linkedinlogin.RNLinkedinLoginModule;
import net.jodybrewster.linkedinlogin.RNLinkedinLoginPackage;
import com.oblador.vectoricons.VectorIconsPackage;

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new VectorIconsPackage(),
          new RNLinkedinLoginPackage(application)
      );
    }
```

**`MainActivity`**: 
```
import com.linkedin.platform.LISessionManager;

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        LISessionManager.getInstance(getApplicationContext()).onActivityResult(requestCode, resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }
``` 

But build failed:
``` 
/android/app/src/main/java/com/myapp/MainApplication.java:83: error: incompatible types: <anonymous ReactNativeHost> cannot be converted to Activity
          new RNLinkedinLoginPackage(this)`
```
new RNLinkedinLoginPackage(this) expect Activity, but on `MainAplication` i hvnt.

And this will fail too:
` LISessionManager.getInstance(getApplicationContext()).onActivityResult(requestCode, resultCode, data);`

**Comment by gorgekara** [comment]
I'm having the same issue implementing this on Android as well - can you please update the docs for React Native > 0.35

**Comment by Richard-Cao** [comment]
Any thing else?
